name: Continuous Integration

on:
  push:
    branches:
      - 'release/*'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      uses: dschep/install-poetry-action@v1.2
    - name: Install dependencies
      run: poetry install
    - name: Lint with flake8
      run: poetry run flake8 . --ignore=W503,E712,E231,E203 --count --max-complexity=10 --max-line-length=88 --show-source --statistics  --exclude=.git,__pycache__,.venv
    - name: Test with pytest
      run: poetry run pytest tests
    - name: Configure publishing credentials
      run: poetry config pypi-token.pypi ${{ PYPI_TOKEN }}
    - name: Configure PyPI repository
      run: poetry config repositories.test https://test.pypi.org/legacy/
    - name: Publish to Test PyPI
      run: poetry publish --repository test
